import { PresetData } from '../../types';

export const slimeSky: PresetData = {
  name: "SlimeSky",
  desc: "Exported from McRD Generator",
  params: {
    usePhysics: true,
    physicsInfluence: 1,
    clampMode: false,
    stabilityThreshold: 1,
    fadeOutRate: 0.8,
    rgbPostProcessing: {
      exposure: 1,
      contrast: 1,
      gamma: 1,
      saturation: 1,
      brightness: 0,
      tint: { r: 1, g: 1, b: 1 }
    },
    renderStyle: "pixelated",
    renderOrder: [
      "fractal",
      "gravity",
      "physics",
      "grayScott",
      "multiDim",
      "gol",
      "lga",
      "walker",
      "media",
      "soca",
      "advection"
    ],
    Dm: 0.1,
    Dc: 1,
    Dw: 5,
    kOn: 0.05,
    kRec: 0.08,
    kSat: 0.05,
    kOff: 0.8,
    feedRate: 0,
    totalDensity: 6,
    boundaryType: "periodic",
    flowX: 0,
    flowY: 0,
    flowScale: 1,
    useWalker: false,
    jitterChance: 0,
    jitterStrength: 0.5,
    noise: 0.02,
    walkerMask: false,
    walkerMaskColor: "#ffffff",
    walkerMaskTol: 0.1,
    walkerMaskInvert: false,
    useGravity: false,
    gravityStrength: 0.5,
    gravityAngle: 0,
    gravityFriction: 0.9,
    gravityMassThreshold: 2,
    useGoL: false,
    golBirth: [3],
    golSurvive: [2, 3],
    golInfluence: 0.5,
    useSoCA: false,
    socaDamping: 0.96,
    socaSpring: 0.01,
    socaDtScale: 1,
    socaSmoothness: 0.5,
    socaSmoothnessEnabled: false,
    socaReactionMix: 1,
    useLGA: false,
    lgaProbability: 0.5,
    lgaAdvection: 1,
    lgaViscosity: 0.1,
    lgaBarrier: 8,
    lgaNoise: 0.05,
    lgaFlowX: 0,
    lgaFlowY: 0,
    lgaWallColor: "#ff0000",
    lgaWallTol: 0.2,
    lgaInfluence: 1,
    lgaVerticalFactor: 1,
    useFractal: false,
    fractalDepth: 2,
    fractalBlockSize: 4,
    fractalBirth: [3],
    fractalSurvive: [2, 3],
    fractalInfluence: 0.4,
    fractalThreshold: 0.4,
    useGrayScott: false,
    gsDa: 1,
    gsDb: 0.5,
    gsFeed: 0.055,
    gsKill: 0.062,
    gsTimeScale: 1,
    gsClamp: true,
    gsInfluence: 1,
    useMultiDim: false,
    coupling: 0.2,
    multiDimZoom: 1,
    multiDimCrossDiff: 0,
    multiDimInfluence: 1,
    brushStrength: 5.4,
    dt: 0.1,
    colorMap: "magma"
  },
  effects: [
    {
      id: "fx_physarum_1787073689027_v73t4",
      type: "physarum",
      name: "Physarum Slime",
      enabled: true,
      isMinimized: false,
      params: {
        agentCount: 200,
        sensorAngle: 0.4,
        sensorDistance: 16,
        rotationAngle: 0.4,
        stepSize: 1.3,
        depositAmount: 1.8,
        decayFactor: 0.85,
        diffuseFactor: 0.22,
        physarumInfluence: 0.2
      }
    },
    {
      id: "fx_reactionKinetics_1787073822690_a5xth",
      type: "reactionKinetics",
      name: "Reaction Kinetics",
      enabled: true,
      isMinimized: false,
      params: {
        bzEpsilon: 0.04,
        bzMu: 0.001,
        bzQ: 0.0008,
        bzF: 1.6,
        bzSpeed: 2.9,
        bzDiffusion: 0.15,
        bzInfluence: 0.9
      }
    },
    {
      id: "fx_multiDim_1787073853839_zv433",
      type: "multiDim",
      name: "Hyper-Dimensionality",
      enabled: true,
      isMinimized: false,
      params: {
        coupling: 0.2,
        multiDimZoom: 1,
        multiDimCrossDiff: 0,
        multiDimInfluence: 1
      }
    },
    {
      id: "fx_flow_1787073870483_rsrge",
      type: "flow",
      name: "Flow Controls",
      enabled: true,
      isMinimized: false,
      params: {
        flowX: 0,
        flowY: -0.7,
        flowScale: 1.0,
        flowAngle: 0,
        flowSpeed: 0
      }
    }
  ],
  seedConfig: {
    type: "perlin",
    intensity: 1,
    seedTarget: { u: 1, v: 0, w: 0 },
    randomThreshold: 0.005,
    perlinScale: 20,
    perlinThreshold: 0.45,
    perlinOctaves: 4,
    perlinSeed: 8476,
    perlinGradient: false,
    gridSpacingX: 20,
    gridSpacingY: 20,
    gridDotSize: 2,
    gridOffset: false,
    shapeType: "circle",
    shapeMode: "single",
    shapeCount: 1,
    shapeSize: 20,
    shapeHollow: false,
    shapePosX: 0.5,
    shapePosY: 0.5,
    mathExpression: "Math.sin(x*0.1)*Math.cos(y*0.1) > 0",
    textString: "McRD",
    textSize: 40,
    textPosX: 0.5,
    textPosY: 0.5
  },
  stabilizeConfig: {
    enabled: false,
    targetDensity: 6,
    strength: 1,
    adjustKOff: true,
    adjustKRec: true,
    adjustKOn: false,
    adjustFeed: false
  },
  automation: [],
  continuousSeeds: [
    {
      id: "cseed_initial_perlin",
      name: "Initial Perlin Seed",
      type: "perlin",
      enabled: true,
      isMinimized: false,
      opacity: 1,
      blendMode: "add",
      x: 0,
      y: 0,
      scaleX: 1,
      scaleY: 1,
      rotation: 0,
      blendIf: {
        enabled: false,
        points: [
          { pos: 0, val: 0, id: "1" },
          { pos: 1, val: 1, id: "2" }
        ],
        smoothness: 0.1
      },
      isStartingSeed: true,
      seedConfig: {
        type: "math",
        intensity: 1,
        randomThreshold: 0.05,
        perlinScale: 20,
        perlinThreshold: 0.45,
        perlinOctaves: 4,
        perlinSeed: 9791,
        perlinGradient: false,
        gridSpacingX: 10,
        gridSpacingY: 10,
        gridDotSize: 2,
        gridOffset: false,
        shapeSize: 20,
        shapeHollow: false,
        seedTarget: { u: 1, v: 0, w: 0 },
        mathExpression: "ny",
        shapeType: "circle",
        shapeMode: "single",
        shapeCount: 5,
        shapePosX: 0.5,
        shapePosY: 0.5
      }
    }
  ]
};
